[book]
authors = ["Keiji Suzuki"]
language = "ja"
multilingual = false
src = "src"
title = "Pine64"

[output.html]
default-theme = "rust"
additional-css = ["theme/variables.css"]
# git-repository-url = "https://github.com/zuki/"

[output.html.fold]
enable = false
level = 0
