[book]
authors = ["Keiji Suzuki"]
language = "ja"
multilingual = false
src = "."
title = "Pine64 Wiki"

[output.html]
default-theme = "rust"
# git-repository-url = "https://github.com/zuki/"

[output.html.fold]
enable = false
level = 0
